export const HOME = {
  emergentLink: "home-emergent-link",
  startTournamentBtn: "home-start-tournament-btn",
  statsBtn: "home-stats-btn",
  reviewBtn: "home-review-btn",
  adminBtn: "home-admin-btn",
};

export const NAV = {
  home: "nav-home",
  train: "nav-train",
  practice: "nav-practice",
  tournament: "nav-tournament",
  sitandgo: "nav-sitandgo",
  stats: "nav-stats",
  review: "nav-review",
  admin: "nav-admin",
};

export const TRAIN = {
  screen: "train-screen",
  heroCards: "train-hero-cards",
  villainSeat: "train-villain-seat",
  heroSeat: "train-hero-seat",
  hud: "train-hud",
  hudPlayers: "train-hud-players",
  hudBlinds: "train-hud-blinds",
  hudPhase: "train-hud-phase",
  actionFold: "action-btn-fold",
  actionCall: "action-btn-call",
  actionMarginal: "action-btn-marginal-call",
  actionRaise: "action-btn-3bet",
  actionAllIn: "action-btn-all-in",
  feedbackOverlay: "train-feedback-overlay",
  feedbackNext: "train-feedback-next",
  feedbackBreakdown: "train-feedback-breakdown",
  restartBtn: "train-restart-btn",
  emptyState: "train-empty-state",
};

export const PLAY = {
  screen: "play-screen",
  setupForm: "play-setup-form",
  newHandBtn: "play-new-hand-btn",
  nextHandBtn: "play-next-hand-btn",
  table: "play-table",
  seatPrefix: "play-seat-",
  heroCards: "play-hero-cards",
  board: "play-board",
  pot: "play-pot",
  actionFold: "play-action-fold",
  actionCheck: "play-action-check",
  actionCall: "play-action-call",
  actionRaise: "play-action-raise",
  actionAllIn: "play-action-all-in",
  raiseSlider: "play-raise-slider",
  raiseInput: "play-raise-input",
  raiseMinBtn: "play-raise-min-btn",
  raiseThirdBtn: "play-raise-third-btn",
  raiseHalfBtn: "play-raise-half-btn",
  raisePotBtn: "play-raise-pot-btn",
  botLog: "play-bot-log",
  errorBanner: "play-error-banner",
  resultBanner: "play-result-banner",
  seatBetPrefix: "play-seat-bet-",
  blinds: "play-blinds",
  helpToggleBtn: "play-help-toggle-btn",
  helpPanel: "play-help-panel",
  soundToggleBtn: "play-sound-toggle-btn",
  turnTimer: "play-turn-timer",
  turnTimerPauseBtn: "play-turn-timer-pause-btn",
  coachPrevBtn: "play-coach-prev-btn",
  coachNextBtn: "play-coach-next-btn",
  coachCounter: "play-coach-counter",
  sessionSummary: "play-session-summary",
  coachAiBtn: "play-coach-ai-btn",
  coachAiSection: "play-coach-ai-section",
};

export const TOURNAMENT = {
  screen: "tournament-screen",
  lobby: "tournament-lobby",
  startBtn: "tournament-start-btn",
  exitBtn: "tournament-exit-btn",
  nextHandBtn: "tournament-next-hand-btn",
  eliminatedScreen: "tournament-eliminated-screen",
  exitedScreen: "tournament-exited-screen",
  newTournamentBtn: "tournament-new-btn",
  backToLobbyBtn: "tournament-back-to-lobby-btn",
  levelBadge: "tournament-level-badge",
  heroNameInput: "tournament-hero-name-input",
  startLevelSelect: "tournament-start-level-select",
};

export const SITANDGO = {
  screen: "sitandgo-screen",
  lobby: "sitandgo-lobby",
  startBtn: "sitandgo-start-btn",
  exitBtn: "sitandgo-exit-btn",
  nextHandBtn: "sitandgo-next-hand-btn",
  bustedScreen: "sitandgo-busted-screen",
  wonScreen: "sitandgo-won-screen",
  exitedScreen: "sitandgo-exited-screen",
  backToLobbyBtn: "sitandgo-back-to-lobby-btn",
  levelBadge: "sitandgo-level-badge",
  heroNameInput: "sitandgo-hero-name-input",
  startLevelSelect: "sitandgo-start-level-select",
};

export const STATS = {
  screen: "stats-screen",
  overallAccuracy: "stats-overall-accuracy",
  streak: "stats-streak",
  totalHands: "stats-total-hands",
  byPosition: "stats-by-position",
  byPhase: "stats-by-phase",
  byAction: "stats-by-action",
  resetBtn: "stats-reset-btn",
};

export const REVIEW = {
  screen: "review-screen",
  list: "review-list",
  empty: "review-empty",
  replayBtn: "review-replay-btn",
  clearBtn: "review-clear-btn",
};

export const ADMIN = {
  screen: "admin-screen",
  jsonTextarea: "admin-json-textarea",
  uploadBtn: "admin-upload-btn",
  totalScenarios: "admin-total-scenarios",
  scenariosList: "admin-scenarios-list",
  clearAllBtn: "admin-clear-all-btn",
  fileInput: "admin-file-input",
};
